# controllers:
#     resource: ../src/Controller/
#     type: annotation

# kernel:
#     resource: ../src/Kernel.php
#     type: annotation

products:
    path: /api/product 
    controller: App\Controller\ProductController::indexAction
    methods : [GET]

products_store:
    path: /api/product_store
    controller: App\Controller\ProductController::createAction
    methods : [POST]

products_show:
    path: /api/product_show/{id}
    controller: App\Controller\ProductController::showAction
    methods : [GET]

products_delete:
    path: /api/product_delete/{id}
    controller: App\Controller\ProductController::deleteAction
    methods : [DELETE]

products_update:
    path: /api/product_update/{id}
    controller: App\Controller\ProductController::products_update
    methods : [PATCH]    

# register:
#   path: /api/register
#   controller: App\Controller\AuthController::register
#   methods: POST

api_login_check:
  path: /api/login_check
  
#   controller: App\Controller\AuthController::getTokenUser

# test:
#   path: /api/test
#   controller: App\Controller\ApiController::test