# controllers:
#     resource: ../src/Controller/
#     type: annotation

# kernel:
#     resource: ../src/Kernel.php
#     type: annotation

products:
    path: /api/product 
    controller: App\Controller\ProductController::indexAction
    methods : [GET]

products_store:
    path: /api/product_store
    controller: App\Controller\ProductController::createAction
    methods : [POST]

products_update:
    path: /api/product_update/{id}
    controller: App\Controller\ProductController::updateAction
    methods : [PUT]
products_show:
    path: /api/product_show/{id}
    controller: App\Controller\ProductController::showAction
    methods : [GET]