# controllers:
#     resource: ../src/Controller/
#     type: annotation

# kernel:
#     resource: ../src/Kernel.php
#     type: annotation

products:
    path: /api/product 
    controller: App\Controller\ProductController::indexAction
    methods : [GET]

products_store:
    path: /api/product_store
    controller: App\Controller\ProductController::createAction
    methods : [POST]